# app/db/migrations/script.py.mako
"""baseline post rls v0.4.0

Revision ID: ccf073c8b981
Revises: 3cf0979df4e8
Create Date: 2026-03-24 23:18:15.620617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccf073c8b981'
down_revision: Union[str, None] = '3cf0979df4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agencies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of agency creation (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agencies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of last update (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agencies', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp - NULL means active',
               existing_nullable=True)
    op.create_index(op.f('ix_agencies_agency_id'), 'agencies', ['agency_id'], unique=False)
    op.create_unique_constraint(op.f('uq_agencies_email'), 'agencies', ['email'])
    op.alter_column('agent_profiles', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('agent_profiles', 'website',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Agent or company website URL',
               existing_nullable=True)
    op.alter_column('agent_profiles', 'company_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Company name (for independent agents without agency)',
               existing_nullable=True)
    op.alter_column('agent_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of agent profile creation (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of last update (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_profiles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp - NULL means active',
               existing_nullable=True)
    op.create_index(op.f('ix_agent_profiles_agency_id'), 'agent_profiles', ['agency_id'], unique=False)
    op.create_index(op.f('ix_agent_profiles_profile_id'), 'agent_profiles', ['profile_id'], unique=False)
    op.create_index(op.f('ix_agent_profiles_user_id'), 'agent_profiles', ['user_id'], unique=True)
    op.alter_column('amenities', 'amenity_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Primary key for amenities (canonical naming)',
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint(op.f('uq_amenities_name'), 'amenities', ['name'])
    op.create_foreign_key(op.f('fk_favorites_property_id_properties'), 'favorites', 'properties', ['property_id'], ['property_id'])
    op.create_foreign_key(op.f('fk_favorites_user_id_users'), 'favorites', 'users', ['user_id'], ['user_id'])
    # Drop check constraint that compares inquiry_status as text (blocks type change).
    op.execute('ALTER TABLE inquiries DROP CONSTRAINT inquiries_inquiry_status_check')
    # Drop status indexes before changing inquiry_status from TEXT to enum.
    op.drop_index('idx_inquiries_new_status', table_name='inquiries')
    op.drop_index('inquiries_status_active_idx', table_name='inquiries')
    op.drop_index('idx_inquiries_status', table_name='inquiries')
    op.execute("""
        ALTER TABLE inquiries
            ALTER COLUMN inquiry_status DROP DEFAULT,
            ALTER COLUMN inquiry_status TYPE inquiry_status_enum
                USING inquiry_status::text::inquiry_status_enum,
            ALTER COLUMN inquiry_status SET NOT NULL,
            ALTER COLUMN inquiry_status SET DEFAULT 'new'::inquiry_status_enum
    """)
    op.alter_column('inquiries', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp',
               existing_nullable=True)
    op.create_index(op.f('ix_inquiries_inquiry_id'), 'inquiries', ['inquiry_id'], unique=False)
    op.create_index(op.f('ix_inquiries_property_id'), 'inquiries', ['property_id'], unique=False)
    op.create_index(op.f('ix_inquiries_user_id'), 'inquiries', ['user_id'], unique=False)
    op.create_index('idx_inquiries_status', 'inquiries', ['inquiry_status'], unique=False)
    op.create_index(
        'inquiries_status_active_idx',
        'inquiries',
        ['inquiry_status'],
        unique=False,
        postgresql_where=sa.text('deleted_at IS NULL')
    )
    op.create_index(
        'idx_inquiries_new_status',
        'inquiries',
        ['property_id', sa.text('created_at DESC')],
        unique=False,
        postgresql_where=sa.text("inquiry_status = 'new'::inquiry_status_enum AND deleted_at IS NULL")
    )
    op.create_check_constraint(
        'inquiries_inquiry_status_check',
        'inquiries',
        "inquiry_status IN ('new', 'viewed', 'responded')"
    )
    op.create_foreign_key(op.f('fk_inquiries_user_id_users'), 'inquiries', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_table_comment(
        'inquiries',
        existing_comment='User inquiries about properties',
        schema=None
    )
    op.alter_column('locations', 'updated_by',
               existing_type=sa.UUID(),
               comment='References auth.users.id (application-level validation only)',
               existing_nullable=True)
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of location creation (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of last update (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'locations',
        existing_comment='Geographic locations for properties with spatial indexing',
        schema=None
    )
    op.alter_column('profiles', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'suspended', name='profile_status_enum'),
               server_default=sa.text("'active'::profile_status_enum"),
               nullable=False)
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of profile creation (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of last update (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('profiles_user_id_unique'), 'profiles', type_='unique')
    op.create_index(op.f('ix_profiles_profile_id'), 'profiles', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_foreign_key(op.f('fk_profiles_user_id_users'), 'profiles', 'users', ['user_id'], ['user_id'])
    op.alter_column('properties', 'listing_status',
               existing_type=postgresql.ENUM('available', 'active', 'pending', 'sold', 'rented', 'unavailable', name='listing_status_enum'),
               comment=None,
               existing_comment='Current availability status of the property',
               existing_nullable=False,
               existing_server_default=sa.text("'available'::listing_status_enum"))
    op.alter_column('properties', 'year_built',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Year the property was built (1950-current_year+2, Nigeria context)',
               existing_nullable=True)
    op.alter_column('properties', 'parking_spaces',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of parking spaces available',
               existing_nullable=True)
    op.alter_column('properties', 'has_garden',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Property has a garden',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('properties', 'has_security',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Property has security features',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('properties', 'has_swimming_pool',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Property has a swimming pool',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('properties', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID of user who last updated this record',
               existing_nullable=True)
    op.alter_column('properties', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp - NULL means active',
               existing_nullable=True)
    op.create_foreign_key(op.f('fk_properties_location_id_locations'), 'properties', 'locations', ['location_id'], ['location_id'])
    op.create_foreign_key(op.f('fk_properties_user_id_users'), 'properties', 'users', ['user_id'], ['user_id'])
    op.drop_table_comment(
        'properties',
        existing_comment='Property listings with location, pricing, and status',
        schema=None
    )
    op.create_foreign_key(op.f('fk_property_amenities_property_id_properties'), 'property_amenities', 'properties', ['property_id'], ['property_id'])
    op.create_foreign_key(op.f('fk_property_amenities_amenity_id_amenities'), 'property_amenities', 'amenities', ['amenity_id'], ['amenity_id'])
    op.alter_column('property_images', 'property_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_foreign_key(op.f('fk_property_images_property_id_properties'), 'property_images', 'properties', ['property_id'], ['property_id'])
    op.create_unique_constraint(op.f('uq_property_types_name'), 'property_types', ['name'])
    op.alter_column('reviews', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp for removed reviews',
               existing_nullable=True)
    op.create_foreign_key(op.f('fk_reviews_property_id_properties'), 'reviews', 'properties', ['property_id'], ['property_id'])
    op.create_foreign_key(op.f('fk_reviews_user_id_users'), 'reviews', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('fk_reviews_agent_id_users'), 'reviews', 'users', ['agent_id'], ['user_id'])
    op.drop_table_comment(
        'reviews',
        existing_comment='User reviews for properties and agents',
        schema=None
    )
    op.alter_column('saved_searches', 'search_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSONB search filters and preferences',
               existing_nullable=False)
    op.alter_column('saved_searches', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp',
               existing_nullable=True)
    op.create_foreign_key(op.f('fk_saved_searches_user_id_users'), 'saved_searches', 'users', ['user_id'], ['user_id'])
    op.drop_table_comment(
        'saved_searches',
        existing_comment='User-saved search criteria stored as JSONB',
        schema=None
    )
    op.alter_column('users', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Internal integer PK for performance',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'supabase_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID from Supabase Auth, used for RLS policies',
               existing_nullable=False)
    op.alter_column('users', 'agency_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='FK to agencies table for multi-tenant support',
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of user last successful login',
               existing_nullable=True)
    op.alter_column('users', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID of user who last updated this record',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of user creation (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of last update (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp - NULL means active',
               existing_nullable=True)
    op.create_index(op.f('ix_users_agency_id'), 'users', ['agency_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_user_role'), 'users', ['user_role'], unique=False)
    op.drop_table_comment(
        'users',
        existing_comment='Core user accounts with role-based access (seeker, agent, admin)',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Core user accounts with role-based access (seeker, agent, admin)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_user_role'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_agency_id'), table_name='users')
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp - NULL means active',
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last update (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of user creation (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_by',
               existing_type=sa.UUID(),
               comment='UUID of user who last updated this record',
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of user last successful login',
               existing_nullable=True)
    op.alter_column('users', 'agency_id',
               existing_type=sa.BIGINT(),
               comment='FK to agencies table for multi-tenant support',
               existing_nullable=True)
    op.alter_column('users', 'supabase_id',
               existing_type=sa.UUID(),
               comment='UUID from Supabase Auth, used for RLS policies',
               existing_nullable=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               comment='Internal integer PK for performance',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'saved_searches',
        'User-saved search criteria stored as JSONB',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(op.f('fk_saved_searches_user_id_users'), 'saved_searches', type_='foreignkey')
    op.alter_column('saved_searches', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp',
               existing_nullable=True)
    op.alter_column('saved_searches', 'search_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSONB search filters and preferences',
               existing_nullable=False)
    op.alter_column('saved_searches', 'search_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'reviews',
        'User reviews for properties and agents',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(op.f('fk_reviews_agent_id_users'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_user_id_users'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_property_id_properties'), 'reviews', type_='foreignkey')
    op.alter_column('reviews', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp for removed reviews',
               existing_nullable=True)
    op.alter_column('reviews', 'review_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('uq_property_types_name'), 'property_types', type_='unique')
    op.alter_column('property_types', 'property_type_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('fk_property_images_property_id_properties'), 'property_images', type_='foreignkey')
    op.alter_column('property_images', 'property_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('property_images', 'image_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('fk_property_amenities_amenity_id_amenities'), 'property_amenities', type_='foreignkey')
    op.drop_constraint(op.f('fk_property_amenities_property_id_properties'), 'property_amenities', type_='foreignkey')
    op.create_table_comment(
        'properties',
        'Property listings with location, pricing, and status',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(op.f('fk_properties_user_id_users'), 'properties', type_='foreignkey')
    op.drop_constraint(op.f('fk_properties_location_id_locations'), 'properties', type_='foreignkey')
    op.alter_column('properties', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp - NULL means active',
               existing_nullable=True)
    op.alter_column('properties', 'updated_by',
               existing_type=sa.UUID(),
               comment='UUID of user who last updated this record',
               existing_nullable=True)
    op.alter_column('properties', 'has_swimming_pool',
               existing_type=sa.BOOLEAN(),
               comment='Property has a swimming pool',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('properties', 'has_security',
               existing_type=sa.BOOLEAN(),
               comment='Property has security features',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('properties', 'has_garden',
               existing_type=sa.BOOLEAN(),
               comment='Property has a garden',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('properties', 'parking_spaces',
               existing_type=sa.INTEGER(),
               comment='Number of parking spaces available',
               existing_nullable=True)
    op.alter_column('properties', 'year_built',
               existing_type=sa.INTEGER(),
               comment='Year the property was built (1950-current_year+2, Nigeria context)',
               existing_nullable=True)
    op.alter_column('properties', 'listing_status',
               existing_type=postgresql.ENUM('available', 'active', 'pending', 'sold', 'rented', 'unavailable', name='listing_status_enum'),
               comment='Current availability status of the property',
               existing_nullable=False,
               existing_server_default=sa.text("'available'::listing_status_enum"))
    op.alter_column('properties', 'property_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('fk_profiles_user_id_users'), 'profiles', type_='foreignkey')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_profile_id'), table_name='profiles')
    op.create_unique_constraint(op.f('profiles_user_id_unique'), 'profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last update (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of profile creation (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'suspended', name='profile_status_enum'),
               server_default=None,
               nullable=True)
    op.alter_column('profiles', 'profile_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'locations',
        'Geographic locations for properties with spatial indexing',
        existing_comment=None,
        schema=None
    )
    op.alter_column('locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last update (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of location creation (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='References auth.users.id (application-level validation only)',
               existing_nullable=True)
    op.alter_column('locations', 'location_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'inquiries',
        'User inquiries about properties',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(op.f('fk_inquiries_user_id_users'), 'inquiries', type_='foreignkey')
    op.drop_constraint('inquiries_inquiry_status_check', 'inquiries', type_='check')
    op.drop_index('idx_inquiries_new_status', table_name='inquiries')
    op.drop_index('inquiries_status_active_idx', table_name='inquiries')
    op.drop_index('idx_inquiries_status', table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_user_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_property_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_inquiry_id'), table_name='inquiries')
    op.alter_column('inquiries', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp',
               existing_nullable=True)
    op.alter_column('inquiries', 'inquiry_status',
               existing_type=sa.Enum('new', 'viewed', 'responded', name='inquiry_status_enum'),
               type_=sa.TEXT(),
               nullable=True,
               comment='Workflow status: new, viewed, responded',
               existing_server_default=sa.text("'new'::inquiry_status_enum"))
    op.create_check_constraint(
        'inquiries_inquiry_status_check',
        'inquiries',
        "inquiry_status = ANY (ARRAY['new'::text, 'viewed'::text, 'responded'::text])"
    )
    op.create_index('idx_inquiries_status', 'inquiries', ['inquiry_status'], unique=False)
    op.create_index(
        'inquiries_status_active_idx',
        'inquiries',
        ['inquiry_status'],
        unique=False,
        postgresql_where=sa.text('deleted_at IS NULL')
    )
    op.create_index(
        'idx_inquiries_new_status',
        'inquiries',
        ['property_id', sa.text('created_at DESC')],
        unique=False,
        postgresql_where=sa.text("inquiry_status = 'new'::text AND deleted_at IS NULL")
    )
    op.alter_column('inquiries', 'inquiry_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('fk_favorites_user_id_users'), 'favorites', type_='foreignkey')
    op.drop_constraint(op.f('fk_favorites_property_id_properties'), 'favorites', type_='foreignkey')
    op.drop_constraint(op.f('uq_amenities_name'), 'amenities', type_='unique')
    op.alter_column('amenities', 'amenity_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               comment='Primary key for amenities (canonical naming)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_agent_profiles_user_id'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_profile_id'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_agency_id'), table_name='agent_profiles')
    op.alter_column('agent_profiles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp - NULL means active',
               existing_nullable=True)
    op.alter_column('agent_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last update (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of agent profile creation (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_profiles', 'company_name',
               existing_type=sa.VARCHAR(),
               comment='Company name (for independent agents without agency)',
               existing_nullable=True)
    op.alter_column('agent_profiles', 'website',
               existing_type=sa.VARCHAR(),
               comment='Agent or company website URL',
               existing_nullable=True)
    op.alter_column('agent_profiles', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('agent_profiles', 'profile_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('uq_agencies_email'), 'agencies', type_='unique')
    op.drop_index(op.f('ix_agencies_agency_id'), table_name='agencies')
    op.alter_column('agencies', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp - NULL means active',
               existing_nullable=True)
    op.alter_column('agencies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last update (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agencies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of agency creation (UTC)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agencies', 'agency_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
